### ISSUE TITLE
Cannot upgrade to v2.0.4 and beyond.

### ISSUE THREAD

**Issue by FeryET** [pdemagny/asdf-teller#2]
Apparently, the release naming scheme has been changed in the main repo:

This plugin expects this:
```sh
$ echo https://github.com/tellerops/teller/releases/download/v2.0.5/teller_2.0.5_Linux_x86_64.tar.gz
```
The new pattern:
```sh
$ echo https://github.com/tellerops/teller/releases/download/v2.0.5/teller-x86_64-linux.tar.xz
```

**Comment by pdemagny** [comment]
Hi @FeryET 

Thanks for bringing this to my attention.
I've released a new version of this plugin that supports installing both legacy teller v1 versions and newer teller v2 versions.
Let me know if it works for you :pray:

**Comment by FeryET** [comment]
> Hi @FeryET 
> 
> Thanks for bringing this to my attention.
> I've released a new version of this plugin that supports installing both legacy teller v1 versions and newer teller v2 versions.
> Let me know if it works for you :pray: 

Hi. I tried the new installation, the only problem is the libssl version mismatch, because teller depends on libssl 1.1.1.

I think we should package it alongside the teller program and override the LD_LIBRARY env variable while executing it.

**Comment by pdemagny** [comment]
The issue with libssl seems related to your environment, installing and/or configuring openssl on a workstation isn't really the scope of this plugin, and I don't wanna mess with people's openssl installation :sweat_smile: 
The original issue has been fixed and this plugin can now download and install newer versions.  
So i'll close this issue :+1:
